[build]
  command = "npm run build"
  publish = ".next"

# Netlify Secrets Scanning Configuration
# The SECRETS_SCAN_OMIT_PATHS allows server-side secrets to be present in build cache
# without triggering the security scanner, as these files are never sent to the client.
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".next/cache/**,.next/server/**,.netlify/**"

# Cache policy for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache policy for Next.js pages (revalidate frequently)
[[headers]]
  for = "/_next/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"
